title: LucasAlt
baseurl: "/"
url: "https://lucasalt.fr"
logo: /assets/images/logo.png
description: >-
  Etudiant de 19 ans, minimaliste, réveur ainsi que développeur front-end.
  Je laisse ma trâce sur cette immense toile qu’est internet.
lang: fr_FR

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
highlighter: none
plugins:
  - jemoji

permalink: "/:title/"

collections:
  news:
    output: true
    permalink: /news/:title/
